# Generated by Django 4.0.3 on 2022-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDfLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=50)),
                ('review_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('stars', models.IntegerField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('useful', models.IntegerField()),
                ('funny', models.IntegerField()),
                ('cool', models.IntegerField()),
                ('stars_avg', models.FloatField()),
                ('useful_avg', models.FloatField()),
                ('funny_avg', models.FloatField()),
                ('cool_avg', models.FloatField()),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
                ('Pos_Word_Count', models.IntegerField()),
                ('Neg_Word_Count', models.IntegerField()),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField()),
            ],
        ),
    ]
