# Generated by Django 4.0.3 on 2022-04-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindflabels',
            name='attributes',
        ),
    ]
