# Generated by Django 4.0.3 on 2022-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_traindflabels_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindflabels',
            name='Prop_pos_neg_words',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='traindflabels',
            name='city',
            field=models.CharField(default='LA', max_length=50),
        ),
        migrations.AddField(
            model_name='traindflabels',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='traindflabels',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='traindflabels',
            name='name',
            field=models.CharField(default='Taco Bell', max_length=100),
        ),
    ]
