# Generated by Django 4.0.3 on 2022-04-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_traindflabels_prop_pos_neg_words_traindflabels_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stars', models.FloatField()),
                ('categories', models.TextField()),
                ('categories_mod', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('review_stars', models.IntegerField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.businessrestaurants')),
            ],
        ),
    ]
