# Generated by Django 4.0.3 on 2022-04-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_businessrestaurants_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='business_id',
        ),
        migrations.DeleteModel(
            name='BusinessRestaurants',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
