# Generated by Django 4.0.3 on 2022-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_businessrestaurants_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_sentiment',
            field=models.IntegerField(default=1),
        ),
    ]
