# Generated by Django 4.0.3 on 2022-04-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_reviews_review_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='business_id',
            new_name='business',
        ),
    ]
