# Generated by Django 4.0.3 on 2022-04-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_business_id_reviews_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews_test',
            name='businessrestaurants_test',
        ),
        migrations.DeleteModel(
            name='BusinessRestaurants_test',
        ),
        migrations.DeleteModel(
            name='Reviews_test',
        ),
    ]
